### ISSUE TITLE
Problems in search results

### ISSUE THREAD

**Issue by RPuglia** [sjarvela/kloudspeaker#26]
Clicking on any file in the search results list I get the following error
TypeError: that._customFolderTypes[that._currentFolder.type].handleAction is not a function
return that._customFolderTypes[that._currentFolder.type].handleAction(ac, item, ...
in kloudspeaker.full.min.js row 19625, col 19 (got with Firebug 2.0.9).
As a result, nothing happens when clicking on any search result row (I expect to be able to download the file). Btw, the search operation and result list are ok.
I'm using php 5.4.3, Firefox 38.0.1. Same issue with Chrome 43.0.2357.65 m.
Any sugestion?
Thanks
Tommaso

**Comment by RPuglia** [comment]
P.S.
Of course I'm using last KS version (2.6.11).
Tommaso

**Comment by sjarvela** [comment]
Fixed, will be in next release.

**Comment by RPuglia** [comment]
Great! Thank very much!
Tommaso

**Comment by jasonPaddy** [comment]
hi Mate,

has this been released into 2.7.3?
search is still broken.

If I click any file, Chrome throw below errors in console:

Uncaught Cannot resolve permission, permissions not fetched kloudspeaker.full.min.js:20
hasFilesystemPermission @ kloudspeaker.full.min.js:20w._canWrite @ kloudspeaker.full.min.js:23w._updateUI @ kloudspeaker.full.min.js:23w._setFolder @ kloudspeaker.full.min.js:23l @ kloudspeaker.full.min.js:6m.fireWith @ kloudspeaker.full.min.js:6e.(anonymous function) @ kloudspeaker.full.min.js:6(anonymous function) @ kloudspeaker.full.min.js:22l @ kloudspeaker.full.min.js:6m.fireWith @ kloudspeaker.full.min.js:6(anonymous function) @ kloudspeaker.full.min.js:6l @ kloudspeaker.full.min.js:6m.fireWith @ kloudspeaker.full.min.js:6d @ kloudspeaker.full.min.js:8send.d @ kloudspeaker.full.min.js:8
kloudspeaker.full.min.js:20 Uncaught Cannot resolve permission, permissions not fetchedhasFilesystemPermission @ kloudspeaker.full.min.js:20w._getCtxObj @ kloudspeaker.full.min.js:23w.itemWidget.init.onClick @ kloudspeaker.full.min.js:23onItemClick @ kloudspeaker.full.min.js:22(anonymous function) @ kloudspeaker.full.min.js:22(anonymous function) @ kloudspeaker.full.min.js:16

**Comment by sjarvela** [comment]
Yes, this should be fixed
